statementArr = [
	'startSwitch("variableName")',
	'endSwitch()',
	'''getComment("This is a comment")''',
	"puts('Something to print')",
	"getClassBeginning('sampleClass')",
	"getClassEnding()",
	'setVar(valueToGet="1", valueToChange="x")',
	'startCase("x")',
	'endCase()',
	'startDefault()',
	'endDefault()',
	"equals(thing1 = 'x', thing2 = 'y', theType='int')",
	'''Or([compare(thing1 = "1", thing2 = "1", theType = "Int"), compare(thing1 = '"lolz"', thing2 = "lolz", theType = "String")])''',
	'''And(["x", "y"])''',
	'''Not("x")''',
	'greaterThan("thing1", "thing2")',
	'lessThan("thing1", "thing2")',
	'Eval('"Evaluate this string."')',
	'concatenateStrings(['"String 1"', '"String 2"'])',
	"endConditionalBlock()",
	"startConditionalBlock()",
	'startIf(condition="x==2")',
	"endIf()",
	'initializeVar(initialValue="1", variableName = "x", variableType = "String", arrayDimensions=None)',
	'getFileExtension()',
	'startForEach(variableName="varInArr", array="theArr", typeInArray="String")',
	'startElse()',
	'startWhile("x==1")',
	'getReturnStatement("toReturn")',
	'compare(theType="String", thing1="str1", thing2="str2")'
	"endElse()",
	"endWhile()",
	"endForEach()",
	"endMethod(methodName='methodName')",
	'endElseIf()',
	'arrayContains(valueToCheck="1", array="arrayOfIntegers")',
	'this("variableName")',
	'''function(functionName="startForEach", returnType="String", isStatic=True, parameterNames=["lang", "array", "variableName", "typeInArray"], parameterTypes = ["String", "String", "String", "String"], body=[])''',
	'startMain()',
	'endMain()',
	'subString(start="1", end="5", theString="strName")',
	'charAt(theString="stringName", index="1")',
	'index(indexList = ["1"], theType="String[]", theObject="ArrayName")',
	'stringLength("stringName")',
	'split(string = "string,test,1", separator = ",")',
	'add(["1","2","3"])',
	'concatenateArrays(["array1", "array2"])',
	'endConstructor()',
	'divide(20, 5)',
	'toString(objectToConvert=1, convertFrom="Int")',
	'startMethod(name="exampleMethod", returnType="int", parameterNames=["param1", "param2"], parameterTypes=["int", "int"], isStatic=True, requiresTheFunctions=False, isDefined=False)',
	'typeOf(1)',
	'callFunctionWithNamedArgs()',
	'getVariableName(True)',
	'getVariableName(False)',
	"lessThanOrEqual('a', 'b')",
	"greaterThanOrEqual('a', 'b')",
	"getArrayInitializer([[1,2], [3,4]])",
	"concatenateStrings(['a', 'b'])",
	'def callFunction("functionName", "fromClass", ["parameter1", "parameter2"]):',
	'semicolon("a statement")',
	'getCorrespondingTypeWithoutBrackets("int")',
	'getCorrespondingTypeWithoutBrackets("string")',
	'getCorrespondingTypeWithoutBrackets("boolean")',
	'startElseIf("condition")',
	'include("fileToInclude")',
	'Error("There is an error!")',
	'args()',
	'seriesOfStatements[1,2,3,4]',
	'compare('"String1"', '"String2"', "String")'
]
